/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	corev1beta1 "sigs.k8s.io/kubefed/pkg/apis/core/v1beta1"
	versioned "sigs.k8s.io/kubefed/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kubefed/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "sigs.k8s.io/kubefed/pkg/client/listers/core/v1beta1"
)

// KubeFedConfigInformer provides access to a shared informer and lister for
// KubeFedConfigs.
type KubeFedConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.KubeFedConfigLister
}

type kubeFedConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeFedConfigInformer constructs a new informer for KubeFedConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeFedConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeFedConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeFedConfigInformer constructs a new informer for KubeFedConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeFedConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().KubeFedConfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1beta1().KubeFedConfigs(namespace).Watch(options)
			},
		},
		&corev1beta1.KubeFedConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeFedConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeFedConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeFedConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1beta1.KubeFedConfig{}, f.defaultInformer)
}

func (f *kubeFedConfigInformer) Lister() v1beta1.KubeFedConfigLister {
	return v1beta1.NewKubeFedConfigLister(f.Informer().GetIndexer())
}
